Repository youngeek-0410/barifac, pull requests merged in 2021-12, with the labels that each got.

#38 feat: add login middleware #23
  fastapi/app/api/v1/auth.py
  fastapi/app/core/auth.py
  fastapi/app/core/exceptions.py
  fastapi/app/core/jwt_handler.py
  fastapi/app/core/log.py
  fastapi/app/core/settings.py
  fastapi/app/dependencies/__init__.py
  fastapi/app/dependencies/auth.py
  fastapi/app/main.py
  fastapi/app/middlwares/__init__.py
  fastapi/app/middlwares/auth.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/auth.py
  fastapi/app/routers/v1/user.py
  fastapi/app/schemas/auth.py
  fastapi/poetry.lock
  fastapi/pyproject.toml
Labels: task:backend, type:feature

#39 feat: add user schema validation #28
  fastapi/app/core/constants.py
  fastapi/app/models/user.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:enhancement

#47 fix: user model
  fastapi/app/db/migrations/env.py
  fastapi/app/models/user.py
Labels: type:bug

#50 Fix/error handling
  fastapi/app/core/exceptions.py
  fastapi/app/crud/user.py
  fastapi/app/schemas/user.py
Labels: type:bug

#48 Issue/41 all model
  fastapi/app/db/migrations/versions/20211204_233131_school.py
  fastapi/app/db/migrations/versions/20211205_001006_department.py
  fastapi/app/db/migrations/versions/20211205_154539_term.py
  fastapi/app/db/migrations/versions/20211205_155003_fix_department.py
  fastapi/app/db/migrations/versions/20211205_155827_teacher.py
  fastapi/app/db/migrations/versions/20211205_230100_subject.py
  fastapi/app/db/migrations/versions/20211206_111924_evaluation.py
  fastapi/app/db/migrations/versions/20211206_114233_attend_subjects.py
  fastapi/app/db/migrations/versions/20211206_115036_teacher_comment.py
  fastapi/app/db/migrations/versions/20211206_115513_subject_comments.py
  fastapi/app/db/migrations/versions/20211206_194958_update_user.py
  fastapi/app/db/migrations/versions/20211206_195600_score.py
  fastapi/app/models/__init__.py
  fastapi/app/models/attend_subject.py
  fastapi/app/models/comment.py
  fastapi/app/models/department.py
  fastapi/app/models/evaluation.py
  fastapi/app/models/school.py
  fastapi/app/models/score.py
  fastapi/app/models/subject.py
  fastapi/app/models/teacher.py
  fastapi/app/models/term.py
  fastapi/app/models/user.py
  fastapi/env.sh
  references/er.drawio
  references/er.png
Labels: task:backend, type:feature, 0.priority:最高

#51 Issue/49 crud class of all models
  fastapi/app/crud/__init__.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/base.py
  fastapi/app/crud/department.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/school.py
  fastapi/app/crud/score.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/term.py
  fastapi/app/crud/user.py
  fastapi/app/db/data.py
  fastapi/app/db/seed.py
  fastapi/app/main.py
  fastapi/app/schemas/__init__.py
  fastapi/app/schemas/attend_subject.py
  fastapi/app/schemas/department.py
  fastapi/app/schemas/evaluation.py
  fastapi/app/schemas/school.py
  fastapi/app/schemas/score.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/teacher.py
  fastapi/app/schemas/term.py
  fastapi/entrypoint.sh
  fastapi/env.sh
Labels: task:backend, type:feature, 0.priority:最高

#60 Issue/56 school api
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/school.py
  fastapi/app/api/v1/user.py
  fastapi/app/core/exceptions.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/school.py
  fastapi/app/routers/v1/user.py
  fastapi/app/schemas/school.py
Labels: task:backend, type:feature

#64 feat: add subject_comment schema, crud, seed #53
  fastapi/app/crud/__init__.py
  fastapi/app/crud/subject_comment.py
  fastapi/app/db/data.py
  fastapi/app/db/seed.py
  fastapi/app/schemas/__init__.py
  fastapi/app/schemas/subject_comment.py
  package-lock.json
Labels: task:backend, type:feature

#63 feat: add teacher_comment scheme, crud, seed #52
  fastapi/app/crud/__init__.py
  fastapi/app/crud/teacher_comment.py
  fastapi/app/db/data.py
  fastapi/app/db/seed.py
  fastapi/app/schemas/__init__.py
  fastapi/app/schemas/teacher_comment.py
Labels: task:backend, type:feature

#66 feat: implement department api #57
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/department.py
  fastapi/app/core/exceptions.py
  fastapi/app/crud/base.py
  fastapi/app/crud/department.py
  fastapi/app/crud/school.py
  fastapi/app/crud/user.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/department.py
  fastapi/app/schemas/department.py
Labels: task:backend, type:feature

#68 fix: add init func in crud class #67
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/score.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/subject_comment.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/teacher_comment.py
  fastapi/app/crud/term.py
Labels: type:bug, task:backend

#70 Issue/61 fix schema and use create schema in seed
  fastapi/app/core/exceptions.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/score.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/subject_comment.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/teacher_comment.py
  fastapi/app/db/data.py
  fastapi/app/db/seed.py
  fastapi/app/schemas/attend_subject.py
  fastapi/app/schemas/department.py
  fastapi/app/schemas/evaluation.py
  fastapi/app/schemas/score.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher.py
  fastapi/app/schemas/teacher_comment.py
  fastapi/app/schemas/term.py
Labels: type:bug, task:backend, type:feature, 0.priority:最高, type:enhancement

#73 fix: add SAME_OBJECT_ALREADY_EXISTS error #71
  fastapi/app/crud/department.py
  fastapi/app/crud/school.py
  fastapi/app/crud/term.py
Labels: type:bug, task:backend

#74 Issue/56 fix school api
  fastapi/app/api/v1/school.py
  fastapi/app/api/v1/user.py
Labels: type:bug, task:backend, type:enhancement

#72 Issue/43 score show edit page
  frontend/src/components/EvaluationTable.tsx
  frontend/src/components/ScoreSlider.tsx
  frontend/src/pages/score_edit/index.tsx
  frontend/src/pages/score_show/index.tsx
Labels: task:frontend, type:feature

#75 Issue/69 add grade field in user model
  fastapi/app/db/data.py
  fastapi/app/db/migrations/versions/20211212_134324_add_grade_in_user.py
  fastapi/app/db/seed.py
  fastapi/app/models/user.py
  fastapi/app/routers/v1/school.py
  fastapi/app/routers/v1/user.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:enhancement

#76 fix: declare constant var of max_length and add Field in schema #55
  fastapi/app/core/constants.py
  fastapi/app/models/attend_subject.py
  fastapi/app/models/comment.py
  fastapi/app/models/department.py
  fastapi/app/models/evaluation.py
  fastapi/app/models/school.py
  fastapi/app/models/score.py
  fastapi/app/models/subject.py
  fastapi/app/models/teacher.py
  fastapi/app/models/term.py
  fastapi/app/models/user.py
  fastapi/app/schemas/attend_subject.py
  fastapi/app/schemas/department.py
  fastapi/app/schemas/evaluation.py
  fastapi/app/schemas/school.py
  fastapi/app/schemas/score.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher.py
  fastapi/app/schemas/teacher_comment.py
  fastapi/app/schemas/term.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:enhancement

#80 Issue/78 term api
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/term.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/term.py
  fastapi/app/schemas/teacher.py
Labels: type:bug, task:backend, type:feature

#82 feat: imprement teacher api #79
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/teacher.py
  fastapi/app/crud/teacher.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/teacher.py
Labels: task:backend, type:feature

#81 feat: add admin_required #77
  fastapi/app/api/v1/auth.py
  fastapi/app/api/v1/department.py
  fastapi/app/api/v1/school.py
  fastapi/app/api/v1/term.py
  fastapi/app/api/v1/user.py
  fastapi/app/core/auth.py
  fastapi/app/core/exceptions.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/base.py
  fastapi/app/crud/department.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/school.py
  fastapi/app/crud/score.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/subject_comment.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/teacher_comment.py
  fastapi/app/crud/term.py
  fastapi/app/crud/user.py
  fastapi/app/dependencies/__init__.py
  fastapi/app/dependencies/auth.py
  fastapi/app/middlwares/auth.py
Labels: task:backend, type:feature

#92 fix: use NotFoundObjectMatchingUuid
  fastapi/app/api/v1/teacher.py
Labels: type:bug, task:backend

#97 fix: raise error when same object exists in create func #96
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/department.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/school.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/term.py
Labels: task:backend, type:enhancement

#94 feat: implement attend_subject api #87
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/attend_subject.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/db/migrations/versions/20211212_210142_update_score.py
  fastapi/app/db/seed.py
  fastapi/app/models/attend_subject.py
  fastapi/app/models/score.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/attend_subject.py
  fastapi/app/schemas/attend_subject.py
Labels: task:backend, type:feature

#98 fix: add ondelete=cascade #93
  fastapi/app/db/migrations/versions/20211213_014042_add_ondelete.py
  fastapi/app/models/attend_subject.py
  fastapi/app/models/comment.py
  fastapi/app/models/department.py
  fastapi/app/models/evaluation.py
  fastapi/app/models/school.py
  fastapi/app/models/score.py
  fastapi/app/models/subject.py
  fastapi/app/models/teacher.py
  fastapi/app/models/term.py
  fastapi/app/models/user.py
Labels: type:bug, task:backend, type:enhancement

#95 Issue/83 firebase login
  .gitignore
  fastapi/app/api/v1/auth.py
  fastapi/app/core/settings.py
  fastapi/app/db/migrations/versions/20211212_193612_grade_nullable_true.py
  fastapi/app/dependencies/auth.py
  fastapi/app/models/user.py
  fastapi/app/routers/v1/auth.py
  fastapi/app/routers/v1/school.py
  fastapi/app/schemas/auth.py
  fastapi/app/schemas/user.py
  fastapi/poetry.lock
  fastapi/pyproject.toml
Labels: task:backend, type:feature

#102 fix: Multiple head revisions are present
  fastapi/app/db/migrations/versions/20211212_210142_update_score.py
Labels: type:bug, task:backend

#104 feat: add subject api #85
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/subject.py
  fastapi/app/crud/subject.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/subject.py
Labels: task:backend, type:feature

#105 feat: add evaluation api #86
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/evaluation.py
  fastapi/app/crud/evaluation.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/evaluation.py
Labels: task:backend, type:feature

#108 Issue/88 score api
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/attend_subject.py
  fastapi/app/api/v1/score.py
  fastapi/app/crud/score.py
  fastapi/app/db/data.py
  fastapi/app/dependencies/auth.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/score.py
Labels: task:backend, type:feature

#109 fix: update user api #91
  fastapi/app/api/v1/user.py
  fastapi/app/crud/user.py
  fastapi/app/middlwares/auth.py
  fastapi/app/routers/v1/user.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:feature

#114 Issue/99 scraping syllabus
  fastapi/app/core/scraping_syllabus.py
  fastapi/app/crud/subject.py
  fastapi/app/db/migrations/env.py
  fastapi/app/db/migrations/versions/20211214_155731_credits_float.py
  fastapi/app/db/migrations/versions/20211214_163908_evaluation_type_length.py
  fastapi/app/db/migrations/versions/20211214_191806_syllabus_info.py
  fastapi/app/db/migrations/versions/20211214_212046_fix_target_department_uuid.py
  fastapi/app/main.py
  fastapi/app/models/department.py
  fastapi/app/models/evaluation.py
  fastapi/app/models/school.py
  fastapi/app/models/subject.py
  fastapi/app/schemas/department.py
  fastapi/app/schemas/evaluation.py
  fastapi/app/schemas/school.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/user.py
  fastapi/env.sh
  fastapi/poetry.lock
  fastapi/pyproject.toml
  references/er.drawio
  references/er.png
Labels: task:backend, type:feature

#120 fix: add option param to filter subject #115
  fastapi/app/api/v1/subject.py
  fastapi/app/crud/base.py
  fastapi/app/routers/v1/subject.py
Labels: task:backend, type:enhancement

#117 fix: restricted the model to be shared by all users #103
  fastapi/app/routers/v1/attend_subject.py
  fastapi/app/routers/v1/department.py
  fastapi/app/routers/v1/evaluation.py
  fastapi/app/routers/v1/school.py
  fastapi/app/routers/v1/subject.py
  fastapi/app/routers/v1/teacher.py
  fastapi/app/routers/v1/term.py
Labels: task:backend, type:feature

#131 Issue/128 add repository
  frontend/src/domains/CommentFactory.ts
  frontend/src/domains/SubjectCommentFactory.ts
  frontend/src/domains/SubjetComment.ts
  frontend/src/domains/Teacher.ts
  frontend/src/domains/TeacherComment.ts
  frontend/src/domains/TeacherCommentFactory.ts
  frontend/src/domains/TeacherFactory.ts
  frontend/src/domains/index.ts
  frontend/src/repositories/AttendSubjectRepository.ts
  frontend/src/repositories/DepartmentRepository.ts
  frontend/src/repositories/EvaluationRepository.ts
  frontend/src/repositories/SchoolRepository.ts
  frontend/src/repositories/ScoreRepository.ts
  frontend/src/repositories/SubjectRepository.ts
  frontend/src/repositories/TermRepository.ts
  frontend/src/repositories/index.ts
Labels: task:frontend, type:feature, 0.priority:最高

#126 Issue/113 attend subjects by term
  fastapi/app/api/v1/attend_subject.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/score.py
  fastapi/app/main.py
  fastapi/app/routers/v1/attend_subject.py
  fastapi/app/schemas/attend_subject.py
  fastapi/app/schemas/department.py
  fastapi/app/schemas/evaluation.py
  fastapi/app/schemas/score.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/teacher.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:feature

#137 fix: change not to add target_department when subject's category is g…
  fastapi/app/core/scraping_syllabus.py
Labels: task:backend, type:enhancement

#136 fix: change schema to read easily #132
  fastapi/app/schemas/score.py
  fastapi/app/schemas/subject.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher_comment.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:enhancement

#139 fix: update repository #138
  frontend/src/repositories/DepartmentRepository.ts
  frontend/src/repositories/EvaluationRepository.ts
Labels: task:frontend, 0.priority:最高

#140 Issue/54 refactor seed data
  fastapi/app/api/v1/subject.py
  fastapi/app/core/scraping_syllabus.py
  fastapi/app/crud/subject.py
  fastapi/app/db/data.py
  fastapi/app/db/migrations/versions/20211215_232532_target_department_to_department.py
  fastapi/app/db/seed.py
  fastapi/app/models/department.py
  fastapi/app/models/subject.py
  fastapi/app/schemas/subject.py
  fastapi/entrypoint.sh
  references/er.drawio
  references/er.png
Labels: type:bug, task:backend, type:enhancement

#143 fix: fix domains #142
  frontend/src/domains/AttendSubjectFactory.ts
  frontend/src/domains/DepartmentFactory.ts
  frontend/src/domains/EvaluationFactory.ts
  frontend/src/domains/ScoreFactory.ts
  frontend/src/domains/Subject.ts
  frontend/src/domains/SubjectCommentFactory.ts
  frontend/src/domains/SubjectFactory.ts
  frontend/src/domains/TeacherCommentFactory.ts
  frontend/src/domains/TeacherFactory.ts
  frontend/src/domains/TermFactory.ts
  frontend/src/domains/UserFactory.ts
  frontend/src/repositories/EvaluationRepository.ts
  frontend/src/repositories/SubjectRepository.ts
Labels: type:bug, task:frontend, 0.priority:最高

#84 Issue/42 add home screen
  frontend/src/components/AddSubject.tsx
  frontend/src/components/DeleteSubject.tsx
  frontend/src/components/EditButton.tsx
  frontend/src/components/SubjectList.tsx
  frontend/src/components/SubjectNameList.tsx
  frontend/src/pages/edit/index.tsx
  frontend/src/pages/index.tsx
Labels: task:frontend, type:feature

#146 Issue/122 update api option param
  fastapi/app/api/v1/attend_subject.py
  fastapi/app/api/v1/department.py
  fastapi/app/api/v1/evaluation.py
  fastapi/app/api/v1/school.py
  fastapi/app/api/v1/score.py
  fastapi/app/api/v1/subject.py
  fastapi/app/api/v1/teacher.py
  fastapi/app/api/v1/term.py
  fastapi/app/crud/attend_subject.py
  fastapi/app/crud/base.py
  fastapi/app/crud/department.py
  fastapi/app/crud/evaluation.py
  fastapi/app/crud/school.py
  fastapi/app/crud/score.py
  fastapi/app/crud/subject.py
  fastapi/app/crud/teacher.py
  fastapi/app/crud/term.py
  fastapi/app/db/seed.py
  fastapi/app/models/__init__.py
  fastapi/app/models/term.py
  fastapi/app/routers/v1/attend_subject.py
  fastapi/app/routers/v1/department.py
  fastapi/app/routers/v1/school.py
  fastapi/app/routers/v1/score.py
  fastapi/app/routers/v1/subject.py
  fastapi/app/routers/v1/term.py
Labels: task:backend, type:enhancement

#133 feat: teacher_comment api #90
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/teacher_comment.py
  fastapi/app/crud/teacher_comment.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/teacher_comment.py
  fastapi/app/schemas/teacher_comment.py
Labels: task:backend, type:feature

#130 feat: add subject_comment api #89
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/subject_comment.py
  fastapi/app/crud/subject_comment.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/subject_comment.py
  fastapi/app/schemas/subject_comment.py
Labels: task:backend, type:feature

#129 fix: add teacher-commnet-model subject-comment-model #107
  fastapi/app/models/__init__.py
  fastapi/app/models/subject_comment.py
  fastapi/app/models/teacher_comment.py
Labels: task:backend, type:feature, 3.priority:低

#150 fix: subject and teacher comment
  fastapi/app/crud/teacher_comment.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher_comment.py
Labels: type:bug, task:backend

#152 feat: change object deletion to be done logically #148
  fastapi/app/crud/base.py
  fastapi/app/db/migrations/versions/20211216_172135_is_active.py
  fastapi/app/models/base.py
  fastapi/app/models/user.py
Labels: task:backend, type:feature

#156 feat: add scores/evaluations endpoint #154
  fastapi/app/api/v1/score.py
  fastapi/app/routers/v1/score.py
Labels: task:backend, type:feature

#161 Issue/116 edit request
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/edit_request.py
  fastapi/app/crud/__init__.py
  fastapi/app/crud/edit_request.py
  fastapi/app/db/migrations/versions/20211217_004430_edit_request.py
  fastapi/app/models/__init__.py
  fastapi/app/models/edit_request.py
  fastapi/app/models/evaluation.py
  fastapi/app/models/subject.py
  fastapi/app/models/user.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/edit_request.py
  fastapi/app/routers/v1/subject_comment.py
  fastapi/app/routers/v1/teacher_comment.py
  fastapi/app/schemas/__init__.py
  fastapi/app/schemas/edit_request.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher_comment.py
  references/er.drawio
  references/er.png
Labels: type:bug, task:backend, type:feature

#166 fix: add subject info to score/evaluation api #163
  fastapi/app/api/v1/score.py
Labels: task:backend, type:enhancement

#167 feat: add ReadUserForOtherUserSchema #164
  fastapi/app/schemas/edit_request.py
  fastapi/app/schemas/subject_comment.py
  fastapi/app/schemas/teacher_comment.py
  fastapi/app/schemas/user.py
Labels: task:backend, type:enhancement

#168 Issue/112 score show page
  fastapi/app/crud/attend_subject.py
  frontend/src/components/CommentModal.tsx
  frontend/src/components/CommentSubmitForm.tsx
  frontend/src/components/EditRequestList.tsx
  frontend/src/components/EvaluationSlider.tsx
  frontend/src/components/SubjectCommentList.tsx
  frontend/src/components/TeacherCommentList.tsx
  frontend/src/pages/score_show/[uuid].tsx
  frontend/src/pages/score_show/index.tsx
  frontend/src/temp/AttendSubjectRepository.ts
  frontend/src/temp/EditRequestRepository.ts
  frontend/src/temp/SubjectCommentRepository.ts
  frontend/src/temp/SubjectRepository.ts
  frontend/src/temp/TeacherCommentRepository.ts
  frontend/src/temp/UserRepository.ts
Labels: type:bug, task:frontend, type:feature

#201 fix: add teacher info in attend subject readable api #184
  fastapi/app/api/v1/attend_subject.py
Labels: task:backend, type:enhancement
