Repository youngeek-0410/barifac, pull requests merged in 2021-11, with the labels that each got.

#24 fix: change db_url to property
  fastapi/app/core/settings.py
Labels: type:bug

#27 Issue/22 user model
  docker-compose.yaml
  fastapi/Dockerfile
  fastapi/app/api/v1/__init__.py
  fastapi/app/api/v1/user.py
  fastapi/app/core/security.py
  fastapi/app/crud/__init__.py
  fastapi/app/crud/user.py
  fastapi/app/db/migrations/env.py
  fastapi/app/db/migrations/versions/20211125_210356_user.py
  fastapi/app/db/seed.py
  fastapi/app/models/__init__.py
  fastapi/app/models/user.py
  fastapi/app/routers/v1/__init__.py
  fastapi/app/routers/v1/user.py
  fastapi/app/schemas/__init__.py
  fastapi/app/schemas/user.py
  fastapi/entrypoint.sh
  fastapi/poetry.lock
  fastapi/pyproject.toml
  setup.cfg
Labels: task:backend, type:feature

#30 Issue/18 setup workflows
  .github/workflows/type.yml
  frontend/next-env.d.ts
  package.json
  tsconfig.json
Labels: task:frontend

#31 Feat(front): add models #25
  frontend/src/domains/AttendSubject.ts
  frontend/src/domains/AttendSubjectFactory.ts
  frontend/src/domains/Comment.ts
  frontend/src/domains/CommentFactory.ts
  frontend/src/domains/Department.ts
  frontend/src/domains/DepartmentFactory.ts
  frontend/src/domains/Evaluation.ts
  frontend/src/domains/EvaluationFactory.ts
  frontend/src/domains/School.ts
  frontend/src/domains/SchoolFactory.ts
  frontend/src/domains/Score.ts
  frontend/src/domains/ScoreFactory.ts
  frontend/src/domains/Subject.ts
  frontend/src/domains/SubjectFactory.ts
  frontend/src/domains/Term.ts
  frontend/src/domains/TermFactory.ts
  frontend/src/domains/index.ts
Labels: task:frontend, type:feature

#29 enhancement(back): change health check response format
  fastapi/app/routers/monitoring/health.py
Labels: task:backend, type:enhancement

#34 feat: setup logger #6
  fastapi/app/core/log.py
  fastapi/app/db/seed.py
  fastapi/app/main.py
  fastapi/poetry.lock
  fastapi/pyproject.toml
Labels: task:backend, type:feature
